using Pmad.Wiki.Services;

namespace Pmad.Wiki.Helpers;

/// <summary>
/// Generic methods to manipulate wiki paths (page paths, actual files paths and media paths)
/// </summary>
internal static class WikiPathHelper
{
    public static string Combine(string? directoryName, string fileName)
    {
        if (!string.IsNullOrEmpty(directoryName))
        {
            return $"{directoryName}/{fileName}";
        }
        return fileName;
    }

    public static (string, string) GetFileNameAndExtension(string fileName)
    {
        // For future use
        if (fileName.EndsWith(".excalidraw.svg", StringComparison.OrdinalIgnoreCase))
        {
            // For Excalidraw files, we want to consider `.excalidraw.svg` as the extension (and not `.svg`).
            return (Path.GetFileName(fileName.Substring(0, fileName.Length - ".excalidraw.svg".Length)), ".excalidraw.svg");
        }
        return (Path.GetFileNameWithoutExtension(fileName), Path.GetExtension(fileName).ToLowerInvariant());
    }

    public static string GenerateSafeFileName(TemporaryMediaInfo mediaInfo)
    {
        var (originalFileNameWithoutExtension, extension) = GetFileNameAndExtension(mediaInfo.OriginalFileName);

        var sanitizedFileName = WikiInputSanitizer.SanitizeMediaFileName(originalFileNameWithoutExtension);

        return $"{sanitizedFileName}_{mediaInfo.TemporaryId}{extension}";
    }

    /// <summary>
    /// If filename seems to be generated by <see cref="GenerateSafeFileName"/>, try to extract the original file name by removing the appended temporary ID.
    /// </summary>
    /// <param name="mediaPath"></param>
    /// <returns></returns>
    public static string GetOriginalFileName(string mediaPath)
    {
        var (fileNameWithoutExtension, extension) = GetFileNameAndExtension(mediaPath);
        var idx = fileNameWithoutExtension.LastIndexOf('_');
        if (idx != -1)
        {
            var possibleTempId = fileNameWithoutExtension.Substring(idx + 1);
            if (Guid.TryParse(possibleTempId, out _))
            {
                fileNameWithoutExtension = fileNameWithoutExtension.Substring(0, idx);
            }
        }
        return fileNameWithoutExtension + extension;
    }

    public static bool IsEditableMedia(string mediaPath)
    {
        return mediaPath.EndsWith(".excalidraw.svg", StringComparison.OrdinalIgnoreCase);
    }

    public static List<string> GetDirectoryParts(string pagePath)
    {
        var pageParts = pagePath.Split('/', StringSplitOptions.RemoveEmptyEntries);

        // Get all parts except the last one (the file name)
        return [.. pageParts.Take(pageParts.Length - 1)];
    }

    public static string ResolveRelativePath(List<string> currentPageDirectoryParts, string relativePath)
    {
        var relativeParts = relativePath.Split('/', StringSplitOptions.RemoveEmptyEntries);
        var resultParts = new List<string>(currentPageDirectoryParts);

        // Process each part of the relative path
        foreach (var part in relativeParts)
        {
            if (part == "..")
            {
                // Go up one level
                if (resultParts.Count > 0)
                {
                    resultParts.RemoveAt(resultParts.Count - 1);
                }
            }
            else if (part != ".")
            {
                // Add the part
                resultParts.Add(part);
            }
            // Skip "." as it means current directory
        }

        return string.Join("/", resultParts);
    }
}
