using System.Text.RegularExpressions;
using Microsoft.AspNetCore.Routing;
using Pmad.Wiki.Helpers;

namespace Pmad.Wiki.Services;

internal class WikiPageEditService : IWikiPageEditService
{
    private readonly IWikiPageService _pageService;
    private readonly ITemporaryMediaStorageService _temporaryMediaStorage;
    private readonly LinkGenerator _linkGenerator;

    private const string IdPlaceholder = "xxxxxxxxxxxx";

    public WikiPageEditService(IWikiPageService pageService, ITemporaryMediaStorageService temporaryMediaStorage, LinkGenerator linkGenerator)
    {
        _pageService = pageService;
        _temporaryMediaStorage = temporaryMediaStorage;
        _linkGenerator = linkGenerator;
    }

    public async Task<string?> CreateEditableMediaFromExisting(IWikiUser user, string mediaPath, CancellationToken cancellationToken = default)
    {
        WikiInputValidator.ValidateEditableMedia(mediaPath);

        var content = await _pageService.GetMediaFileAsync(mediaPath, cancellationToken);
        if (content == null) 
        {
            return null;
        }

        // If filename have been generated by GenerateSafeFileName, we try to restore the original file name for better user experience.
        var fileName = WikiPathHelper.GetOriginalFileName(mediaPath);

        return await _temporaryMediaStorage.StoreEditableTemporaryMediaAsync(user, fileName, content, new EditableMediaInfo() { IsEditable = true, InitialGitPath = mediaPath }, cancellationToken);
    }

    public async Task SavePageAsync(string pageName, string? culture, string content, string commitMessage, IWikiUser author, CancellationToken cancellationToken = default)
    {
        WikiInputValidator.ValidatePageName(pageName);

        var mediaFiles = new Dictionary<string, WikiMediaFile>();
        var updatedContent = content;

        var wikiBaseUrl = _linkGenerator.GetPathByAction("TempMedia", "Wiki", new { id = IdPlaceholder })!;

        var escapedWikiBaseUrl = Regex.Escape(wikiBaseUrl);
        var pattern = escapedWikiBaseUrl.Replace(Regex.Escape(IdPlaceholder), "([a-f0-9]+)");
        var usedTempIdRegex = new Regex(pattern, RegexOptions.IgnoreCase);

        var usedTempIds = usedTempIdRegex.Matches(updatedContent)
            .Select(m => m.Groups[1].Value)
            .Distinct()
            .ToList();

        if (usedTempIds.Count > 0)
        {
            var tempMedia = await _temporaryMediaStorage.GetUserTemporaryMediaAsync(author, cancellationToken);

            var pageDirectory = WikiFilePathHelper.GetDirectoryName(pageName);
            var pageSimpleName = Path.GetFileName(pageName);
            var ownedMediaPath = WikiPathHelper.Combine(pageDirectory, $"medias/{pageSimpleName}/");

            foreach (var tempId in usedTempIds)
            {
                if (tempMedia.TryGetValue(tempId, out var mediaInfo))
                {
                    var mediaContent = await _temporaryMediaStorage.GetTemporaryMediaAsync(author, tempId, cancellationToken);
                    if (mediaContent != null)
                    {
                        string markdownRelativePath;

                        if (mediaInfo.EditableMediaInfo?.IsEditable == true
                            && mediaInfo.EditableMediaInfo.InitialGitPath != null
                            && mediaInfo.EditableMediaInfo.InitialGitPath.StartsWith(ownedMediaPath))
                        {
                            // If the media is editable and has an initial git path that indicates it belongs to the same page, we treat it as an update to existing media
                            var mediaPath = mediaInfo.EditableMediaInfo.InitialGitPath;
                            markdownRelativePath = string.IsNullOrEmpty(pageDirectory) ? mediaPath : mediaPath.Substring(pageDirectory.Length + 1);

                            mediaFiles[mediaPath] = new WikiMediaFile(mediaContent, IsUpdate: true);
                        }
                        else
                        {
                            var finalFileName = WikiPathHelper.GenerateSafeFileName(mediaInfo);
                            markdownRelativePath = mediaInfo.EditableMediaInfo?.IsEditable == true ? $"medias/{pageSimpleName}/{finalFileName}" : $"medias/{finalFileName}";
                            var mediaPath = WikiPathHelper.Combine(pageDirectory, markdownRelativePath);
                            
                            mediaFiles[mediaPath] = new WikiMediaFile(mediaContent, IsUpdate: false);
                        }

                        var tempMediaUrl = wikiBaseUrl.Replace(IdPlaceholder, tempId);

                        // Update content to replace temporary URLs with permanent relative paths
                        updatedContent = updatedContent.Replace(tempMediaUrl, markdownRelativePath);
                    }
                }
            }
        }

        await _pageService.SavePageWithMediaAsync(
            pageName,
            culture,
            updatedContent,
            commitMessage,
            author,
            mediaFiles,
            cancellationToken);
    }
}
