// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pmad.Wiki.Demo.Entities;

#nullable disable

namespace Pmad.Wiki.Demo.Migrations
{
    [DbContext(typeof(DemoContext))]
    partial class DemoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Pmad.Wiki.Demo.Entities.DemoUser", b =>
                {
                    b.Property<int>("DemoUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GitEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GitName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SteamId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DemoUserId");

                    b.ToTable("DemoUser", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
